### ISSUE TITLE
Bug in onet/websocket

### ISSUE THREAD

**Issue by ineiti** [dedis/onet#169]
Now: if `onet.Client.Send` is called on a `NewClientKeep`, the connection will be kept even if we have a different command. So:

```
c := NewClientKeep("Skipchain")
c.Send(dst, "StoreSkipChain", sc)
c.Send(dst, "GetUpdateChain", last)
```

does not work, because the first send makes a connection, and the second send uses the same connection, connected to the same endpoint, which is still `StoreSkipChain` in that case.

Wanted: also store endpoint used (`path`) and re-connect if the path is different.

**Comment by nikkolasg** [comment]
Or rethink the whole thing ^^ ?
I'm wondering if this approach using the URL is the right one... From what I see in other code using websocket, it's that there is ONE url and they use it in the same way as a TCP stream and that's it... Why should we do it differently.. ? I mean what's the advantage of using different URL for us ? Because here it again introduces a complexity in which I lack to see the benefit...

**Comment by ineiti** [comment]
There are two parts:
1. using websockets
2. `NewClient`

1. seems to be OK to me (section 1.5 and 3 in https://tools.ietf.org/html/rfc6455), as the only other alternative that fits "usable by javascript" would be to have a REST interface. WebRTC seems to be the wrong solution here.

So we could change 2., the `NewClient` - this would be a list of things I'd like to have in there:
- easy re-use of existing connections
- can of worms: possibility of direct inter-node communication without having to do the websocket-setup
- implementation in java/python/...

**Comment by ineiti** [comment]
So if we go along with this, I propose that `NewClientKeep` has a list of connections, one for each `ServerIdentity`/`path` combination, and that it checks if the connection is available, if it is, it uses it, else it creates a new connection.

There should also be a maximum number of connections held, and then delete either the oldest or a random one (second option would be the easiest if you use a `map`)

**Comment by bford** [comment]
Not sure if "maximum number of connections" is a good idea; fixed values like that tend to create unexpected problems later.  Unless (a) there is some meaningful basis on which to set that maximum; or (b) the maximum is pretty insanely large and just meant mainly as a sanity-check and not a garbage collection mechanism.

If you're looking for a garbage collection mechanism here, I'd suggest an idle-timeout of some kind would be better.  TCP sockets normally have idle-timeout features that you can set using appropriate socket options; not sure if Go consistently exposes those options, but if so, that might be a good way.  Otherwise, a similar mechanism implemented at the Go level might do instead.

**Comment by nikkolasg** [comment]
In my opinion, when we start saying things like : 
> NewClientKeep has a list of connections, one for each ServerIdentity/path combination

while using Websocket which is more a "bidirectional connection stream over HTTP" type ~= TCP over HTTP, it sounds like we're doing stg sketchy. 
In short, I think we can do better than using different connections to talk to the same server !

For example, would it be possible to do stg like the network library which dispatch message to the right recipient according to the type of the messages ? It's multiplexing thanks to the type of the message and not a fixed URL-endpoint.
So `Service` would register the message they expect from external clients, such like `RegisterAPI(&AddSkipBlock{},myFunctionToCall)`.

Looking very quickly at websocket.go it seems it's doable without changing the API but I'm not 100% sure.

**Comment by nikkolasg** [comment]
Here's my proposition to avoid doing multiple connections to the same server and still keep the same API:

### What's happening currently

 Websocket registers path to the web handler using the service name, such as `/skipchain/`. When a client sends a message, it sends the message a to the url `ws://<ip_address>/<service_name>/<golang_struct_name>`. The websocket handler strips the name of the service, and gives the "struct name" to the service as well as the buffer. The websocket handler does not interpret in any way the buffer. Upon reception, the service has the name of the endpoint = structure (/<golang_struct_name>) and the raw buffer. It can then unmarshal the buffer.
The message being sent/received through the netwok is the message being sent/received by the service, there is no "wrapper". 

### Problem

The client connects using the "full" path such as `ws://<ip_address>/<service_name>/<golang_struct_name>`. Therefore the same connection can't be used to send another message because the endpoint is not the same.

### What can be done

The websocket can "peek" inside the raw buffer to see what is the type of the message being sent. Remember that our marshalling routines preprend the size + type of the message in front of the message. 
That way:
+ The websocket client only connects to `ws://<ip_address>/<service_name>` and can re-use a connection to send different messages,
+ the websocket handler can correctly create the fake "endpoint" /<golang_struct_name/ and gives that to the Service as usual. 

The API stays the same only the implementations will have to change. Instead of embedding the struct-name in the URL, just embed the service name.

Later, we'll need to even further restrict that to just embed the ip address in the URL since we may also want to use the same connection for different services. It can be done if we transform our `websocket` server into a full blown `network.Host`. Anyway, this is not needed right now as it's not the scope of this issue.
