### ISSUE TITLE
Check if `graceful` is needed in `websocket`

### ISSUE THREAD

**Issue by ineiti** [dedis/onet#17]
I thought I need `websocket`, so we can close the server correctly, but perhaps not?

**Comment by nikkolasg** [comment]
In the PR #15 , you introduced the `NoSignalHandling` parameter to the graceful server. (https://github.com/tylerb/graceful/blob/master/graceful.go#L56)
The question indeed is do we still need this graceful server :
+ Using the `NoSignalHandling`, a SIGINT nows kills the running process *without* any graceful stopping
+ We only use the `Stop()` in the tests
+ We always kill our server by CTRL-C

I think we could shift the graceful library to only be used in the tests, since that does not make sense to use a graceful shutdown library when we don't use it really.

**Comment by ineiti** [comment]
Possible, but probably too clumsy to have both. I propose we:

- either keep `graceful` to keep the tests happy
- go back to `http.Server` and add an exception for the `log.AfterTest` if it sees a `websocket.start`

**Comment by nikkolasg** [comment]
> but probably too clumsy to have both

Since we are using `LocalTest` in most of our tests, it should be fairly easy to have a `newWebSocketServer` method which uses the graceful thing, unexported, called only from `NewLocalTest` for each `onet.Conode` created. I think this is do-able since the `NewWebSocket` does not start yet the server, so it's possible to change the inner fields of the `Websocket` struct before calling `conode.Start()`.
