### ISSUE TITLE
Input validation

### ISSUE THREAD

**Issue by ineiti** [dedis/onet#189]
Under certain circumstances, a conode will fail if it receives illegal input in either the binary or the websocket-port. Unfortunately I don't have a specific example, but we should look at the input-paths from both the binary and the websocket-receivers and make sure that errors are caught, such as:
- illegal messages
- too big messages

So all possible and imaginable error-handling should be done. An easy random-message-catcher would be to add a sha256 to all messages sent over the network.

Another way would be to push (finally) the TLS-implementation for the binary receiver.

And finally we could do some fuzzy-testing.

**Comment by nikkolasg** [comment]
> And finally we could do some fuzzy-testing.

Yes yes yes !! I'd be happy to try that out !

The TLS implementations won't be a drop-in solutions to this problem anyway, so it may be worth doing both in parallel ;)

**Comment by ineiti** [comment]
This is in onet/network/tcp.go:

```
func (c *TCPConn) receiveRaw() ([]byte, error) {
```

**Comment by nikkolasg** [comment]
For 1. absolutely right !
For 2. I don't see the exact utility in that. I can compute a hash of random blob and append it and send it over the wire. What exactly are you trying to protect from ? 
For 3., I would highly prefer to see something solid as TLS instead of "sign that message". I don't see the direct benefits for us because we still won't be able to say our communications are secured (because just a signature is not enough ;) )

**Comment by ineiti** [comment]
2. protection against random strings
3. yes, probably not worth it. Here the benefit would be to have a track of who sent packages, and then being able to remove that node if there are multiple bad packets.

Adding TLS would of course be much better, but we're still a couple of steps away fromthis.

**Comment by IlyaMarkovMipt** [comment]
3. Add possiblity for conodes to say on network layer that it wants to accept messages from exact conodes, create blacklists, blame some conode in case of byzantine behavior.

**Comment by nikkolasg** [comment]
> protection against random strings
But this is not a protection, it just pushes the problem to the next step of generating a hash for a random string.
3. I see your point but the definition of "bad packets" for me is 
     - either the size is illegal (too high or else)
     - either there's not enough data to read according to the size
     - either the data can not be unmarshalled properly using protobuf encoding

With the current architecture of `network.Router` that it knows all publics keys of its connections, and using these rules it can already be done. Adding a signature here would only makes things more complex (i.e. adding more cases of "things that are bads").

4. > Add possiblity for conodes to say on network layer that it wants to accept messages from exact conodes, create blacklists, blame some conode in case of byzantine behavior.

Yes, that's a good feature I agree but theses features have to rely on a proper authentication / encryption mechanism below, otherwise they can not be guaranteed.  We can not have this feature with signatures only. It's like 3. it needs this reliable layer below.

Anyway, I should probably not engage too much in onet discussions like this anymore, but I really do feel it's a shaky solution to a common problem. These are the kinds of "roll your own crypto" stuff (while common solutions exist) that makes cryptocurrencies lose millions of dollars...
There's a lot of other stuff to be done in onet too... 

I'll stop here :)

**Comment by ineiti** [comment]
you're definitively right, and I'm looking forward to the day we have _real_ TLS ;) And, please, don't stop interfering! Just mind the young padawas ;)

OK, let's do the hashing, to make sure that the messages at least are not random port-scanners. But let's drop the signature/encryption thingie.

**Comment by nikkolasg** [comment]
> OK, let's do the hashing, to make sure that the messages at least are not random port-scanners.

Ok so this is what you want to protect from. Is this possible that port scanners can annoy us ? IIRC any "incoming connection" HAVE to send first its `ServerIdenttiy` so the receiver side knows who's connecting to it. So a random port scanner won't probably send anything like that and therefore the connection won't probably never get registered and never "looped on". Am I missing stg ... ?

**Comment by Daeinar** [comment]
@ineiti Could you please explain to me what you mean with "random strings" and how the additional hash should protect against them? I don't see the added bonus from the current discussion, unfortunately.

**Comment by ineiti** [comment]
If a 'scanner' sends a packet to a conode, I'd like to be able to detect that packet as being random. So we can add a `magic start sequence`, or define this magic start sequence as being the hash of the header (which is just the length of the message for the moment).

So a conode would first read the header, verify the hash, and only then allocate the appropriate size for the message.

Does that make sense? But it might be enough to have a magic start sequence.

**Comment by ineiti** [comment]
@nikkolasg - IIRC the very first bytes are the size of the packet, even before the `ServerIdentity`. This is what kills the conodes for the moment.

**Comment by nikkolasg** [comment]
> This is what kills the conodes for the moment.

You seem to base your proposal on an real life experience, what has it been ? How the first bytes for the length are killing a conode ? OOM ?

Sorry but again, if we do the 1) limit lenght of a packet and 2) close the connection if the packet is not a correct protobuf packet (or more generally, is invalid according the list I wrote above), what would a port scanner can do more than with the "hash technique" ?

**Comment by ineiti** [comment]
yes, it's OOM. This is why Amogh and Lefteris don't have a conde...

I think it's good to refuse bad packets as soon as possible. So either a hash or some magic bytes should be added.

**Comment by nikkolasg** [comment]
> This is what kills the conodes for the moment.

Why do you think the first few bytes are related to the OOM problem ? How do you know it's related to the number of incoming connections ? It could also be any kept-in-reference buffers, or go routines non closed or what ever we use all the way up to the stack. 

> I think it's good to refuse bad packets as soon as possible

Yes and a 1) correct length and 2) correctly protobuf encoded message seems like early enough in the process no ? I hardly see the reason why you keep insisting on detecting before the length bytes, as it does not change anything to what an attacker can do and do not change anything to what a port scanner can do. As soon as you limit the length, the port scanner will send a random length that may be valid, and if so, the protobuf following will probably be invalid and that should be it. If the OOM is really in that tight tiny spot (which i have absolutely no clue and would love to hear your thoughts about it), then it's merely hiding the issue for one specific attack scenario instead of fixing it. and I believe that fixing that issue in Golang should not be that hard (compared to C/C++ code), but can take time for sure.

Besides those techniques disagreement, I'm also afraid that "just like that" we're increasing the complexity of our network wire protocol without really realizing it (this is not the purpose of the issue). I don't think it should be taken as a light decision to add something like that.
