### ISSUE TITLE
onet-channels block if there are too many messages waiting

### ISSUE THREAD

**Issue by ineiti** [dedis/onet#219]
In line

https://github.com/dedis/onet/blob/master/treenode.go#L168

onet blocks if the message-queue gets too big. We can either increase the queue-size in `RegisterChannel` or put the above call to `Send` in a go-routine.

**Comment by nikkolasg** [comment]
Another solution would be to put overflows message of any type into a `overflowQueue`. It would be the same as resizing the channel *dynamically* which I'm not sure is possible (?). But there needs to be a way to control how much overflowing do we allow. 

My comment on the "go routine" solution:
That's one idea we had back at the time though but I was not very super happy with it because one goroutine for one message is really huge, even though goroutines are lightweight, onet do sends a lot of message so... I'm not sure but at the same time we use this technique for the Service already. Services though are not supposed to send that much message between each others.
Another problem if we switch to goroutine is that we loose the strict ordering of the messages. Ludo had this problem 2 days ago where his service message were **sent** in the right order but not **received** in the right order (`A` -> `B` for sending, but `B` -> `A` for recepetion) It's because go routines have no guarantee to start after another one

**Comment by nikkolasg** [comment]
That's actually related to an old issue we had for a long time we just deleted: the dispatching of messages in onet. Back at the time, I wanted to implement some kind of "goroutine pools" so each message would get dispatched by one go routine but there's only a fixed amount of goroutine per pools (or it can be adjusted dynamically but under controlled settings).

**Comment by nikkolasg** [comment]
Following this idea: http://marcio.io/2015/07/handling-1-million-requests-per-minute-with-golang/

**Comment by ineiti** [comment]
Hmm, we'll have to take care how we use it. Let's say we have 2 workers and a worker queue for all messages, and the protocol on node I does:

1. wait for message A
2. wait for 2 messages B

Now node II sends 2 messages B, and node III sends 1 message A. The two workers in node I would take the 2 messages B, block, and the message A would never be handled. So we'd have the same problem as before. 

So we'd need one worker-queue per message-type to make this work.

**Comment by nikkolasg** [comment]
First of all, you will not put 2 workers in the pool but much more ;)
Secondly, this discussion may have no end if we do not clearly state our goal. 
--> Should we programmatically stop processing messages if a node is too "loaded" ?
       --> If Yes, precise "too loaded", and any solutions that allows us to control the processing power/memory (like goroutines pools or channels). That means the system can loose messages if it is too loaded.
       --> If No, then that means we let the OS / system panic when it is OOM.

I guess you know my opinion ... ;)

**Comment by ineiti** [comment]
Hmm - this should in fact be a configuration option. For simulations and such I think it is OK if the node tries as hard as possible to do as the user asks him to, even if it means hara-kiri. We could let the limit at 100 messages, and if it goes above, print a warning and run go-routines. Then add a method `RegisterChannelSize` where you can change the size of the channel, so if you're running large simulations, you can actually increase the channels.

Or we could `Error` and delete the protocol, so the user _has_ to use `RegisterChannelSize`.

I prefer having a warning and resorting to `go`-routines, plus having the `RegisterChannelSize`. But perhaps an `Error` with a good message would be cleaner.

**Comment by nikkolasg** [comment]
> RegisterChannelSize

I don't get why we need this method. IF we are OK with letting the node enter harakiri mode, then the simplest go routine approach is fine for me, why do the user need to do stg special ?

I'm sure it would be the simplest thing to do but I'm not sure we will benefit that much of going harakiri. And as you said, this must NOT come in place anywhere else than for simulation purposes..

**Comment by nikkolasg** [comment]
> Or we could Error and delete the protocol, so the user has to use RegisterChannelSize.

+1
