### ISSUE TITLE
CreateRoster makes keys in a fishy way

### ISSUE THREAD

**Issue by jeffallen** [dedis/onet#282]
func (s *SimulationBFTree) CreateRoster

creates the private keys for the servers in the identity by picking one and then incrementing them by one with Scalar.Add().

1. This is insecure. It is in the simulation context, so not so so dangerous, but really? Could it be for easier debugging? Strange.
2. For suites which implement key hiding, this is invalid. Key x and x+1 are not both guaranteed to be hideable.
3. The Public key is incorrectly set to Base() instead of to Mul(kp.Secret+1, nil). Hard to understand how this works at all.

Need feedback from the author of this code before mucking about with it.

**Comment by nikkolasg** [comment]
1. This is indeed insecure but it is for simulation purposes: making it in such a way is way more faster than creating them from random. @ineiti made this when we needed to generate up to tens of thousands of keys for CoSi (up to 64K).
2. As written in the interface of `Hiding` the caller should re-randomize the `cipher.Stream` argument to try again. And we anyway don't test that a given key is hideable by default with a given random (and that most likely won't make sense since the result may depend on the given randomness).
3. 
```
s_1 = <secret>
P_1 = s_1 * G
```
then
```
s_2 = s_1 + 1
P_2 = P_1 + G = (s_1 * G) + 1 * G = (s_1 + 1) * G = s_2 * G
```

**Comment by jeffallen** [comment]
Ah, right, I missed the fact it is "add Base". I thought it was "set to Base".

Closing this because it is "desired fishiness".
