### ISSUE TITLE
onet simulation RunWait

### ISSUE THREAD

**Issue by ineiti** [dedis/onet#323]
With the change of having real `time.Duration` instead of `int`, `RunWait` and `ExperimentWait` in the `simulation.toml`-files don't behave as expected.

Need to change:
- either print an error if `RunWait` or `ExperimentWait` misses time-unit
- or suppose seconds if `RunWait` or `ExperimentWait` are integers

Files (at least):
simul/build.go
simul/platform/platform.go

**Comment by jeffallen** [comment]
The previous behavior was "if there was an error getting runwait from the toml file, then silently use runwait from the command line (or the default of 180s)".

The fixed behavior will be: "if runwait is not in the config file, default. if it is and parses, use it. If not, throw a fatal error so that the problem HAS to be fixed."
