### ISSUE TITLE
Change roster ID

### ISSUE THREAD

**Issue by ineiti** [dedis/onet#334]
Now: Roster-ID is generated as a `uuid.NewV4` and as such is unique.

Problem: Two rosters with the same list of `ServerIdentity`s can have a different ID, and as such will be retransmitted

Proposition: change Roster-ID to be the sha256 of the concatenation of the public keys of the `ServerIdentity`s

**Comment by jeffallen** [comment]
Also: then Roster.List need to be privatized.
Benefit: the javascript guys do not need to find/write a UUID library, they can use sha256, which they already have.

But: to calculate a stable sha256 for a given list, the public keys need to be sorted.

To investigate and decide if this fits for onet v2.

**Comment by nikkolasg** [comment]
We may need to rethink the larger problem here. We have all these IDs:
```
type Token struct {
	RosterID RosterID
	TreeID   TreeID
	ProtoID   ProtocolID
	ServiceID ServiceID
	RoundID   RoundID
	TreeNodeID TreeNodeID
}
```
The ID that can be generated deterministically are:
 - RosterID
 - TreeID
 - ProtoID
 - ServiceID
 - TreeNodeID
The only one that *has* to have a random component in it is RoundID. This is because we want to be able to run the same protocol over the same tree in parallel.
How to make a consistent / unified way to handle those two cases ?
Here, I'm afraid it will only get worse if we "just" replace `RosterID` by a `sha256`: some IDs will be `sha256`, others not, which one is it. It's already a "hard enough" to reconstruct that ID in other languages because of some special construct with the URLs and such, but if we change the generation method too, it'll become worse.

At this time of the day, my first thought is to change every deterministic ID to sha256, and the RoundID is a simple 32 bytes nonce.

**Comment by jeffallen** [comment]
The bus has left the station. The camel is out of the oasis. The kiwi has flown the coop.
