### ISSUE TITLE
Non-Integer parameters of simulation not in resulting csv-file

### ISSUE THREAD

**Issue by pablo-lo** [dedis/onet#446]
In https://github.com/dedis/onet/blob/master/simul/monitor/stats.go#L339, parameters of the simulation are only added to the resulting csv file when they can be parsed into an Integer.

Since other types might be used as well to parameterize a simulation, they should also be parsed.

**Comment by jeffallen** [comment]
@adderbyte try changing the type of static to string in https://github.com/dedis/onet/blob/master/simul/monitor/stats.go#L26

So when simulation parameters arrive, they just get remembered instead of parsed into ints, and when they are written into the CSV file, they can be written as strings.

(I'm not 100% certain this is possible and what we want, but take a little try at it, show us your results or tell us what your problem was, and then we'll see.)

As for TDD (test driven development), take a look at TestCounterIOMeasureRecord, where WriteValues is called. You might be able to use it to create the situation where there's a string that is not being printed in the output (if you add code that parses the CSV generated by the test to check) and then once you've added your code the CSV will have the right thing in it. You don't need to write a new test from scratch if you can find one that is already covering the code and hack it up a bit.
